id: P010413
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28959
  title: བོད་ཀྱི་འབྱུང་རྩིས་རྣམ་གཞག
  author: ''
  volumes:
    825b8df0d6da42a08d449da2a925f531:
      image_group_id: I5775
      title: ''
      volume_number: 1
      total_pages: 252
      base_file: v001.txt
