id: I0890C481
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T04:10:06+00:00'
last_modified: '2022-06-08T13:24:34.659326+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28959
  title: བོད་ཀྱི་འབྱུང་རྩིས་རྣམ་གཞག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CB6B:
      image_group_id: I5775
      title: ''
      total_pages: 252
      order: 1
      base_file: CB6B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
